//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootcampCapstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int categoryID { get; set; }
        public string category1 { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
